export const CROP_CATALOG = [
  { name: 'Rice', seasons: ['Kharif', 'Rabi', 'Summer'] },
  { name: 'Wheat', seasons: ['Rabi'] },
  { name: 'Maize', seasons: ['Kharif', 'Rabi', 'Summer'] },
  { name: 'Barley', seasons: ['Rabi'] },
  { name: 'Sorghum (Jowar)', seasons: ['Kharif', 'Rabi'] },
  { name: 'Pearl Millet (Bajra)', seasons: ['Kharif'] },
  { name: 'Finger Millet (Ragi)', seasons: ['Kharif', 'Rabi'] },
  { name: 'Pigeon Pea (Arhar/Tur)', seasons: ['Kharif'] },
  { name: 'Chickpea (Gram)', seasons: ['Rabi'] },
  { name: 'Green Gram (Moong)', seasons: ['Kharif', 'Summer'] },
  { name: 'Black Gram (Urad)', seasons: ['Kharif', 'Rabi'] },
  { name: 'Lentil (Masoor)', seasons: ['Rabi'] },
  { name: 'Field Pea', seasons: ['Rabi'] },
  { name: 'Cowpea', seasons: ['Kharif', 'Summer'] },
  { name: 'Groundnut', seasons: ['Kharif', 'Rabi', 'Summer'] },
  { name: 'Soybean', seasons: ['Kharif'] },
  { name: 'Mustard', seasons: ['Rabi'] },
  { name: 'Rapeseed', seasons: ['Rabi'] },
  { name: 'Sunflower', seasons: ['Kharif', 'Rabi'] },
  { name: 'Sesame (Til)', seasons: ['Kharif'] },
  { name: 'Safflower', seasons: ['Rabi'] },
  { name: 'Castor', seasons: ['Kharif'] },
  { name: 'Cotton', seasons: ['Kharif'] },
  { name: 'Jute', seasons: ['Kharif'] },
  { name: 'Sugarcane', seasons: ['Year-round'] },
  { name: 'Potato', seasons: ['Rabi'] },
  { name: 'Onion', seasons: ['Kharif', 'Rabi'] },
  { name: 'Garlic', seasons: ['Rabi'] },
  { name: 'Tomato', seasons: ['Kharif', 'Rabi', 'Summer'] },
  { name: 'Brinjal (Eggplant)', seasons: ['Kharif', 'Rabi', 'Summer'] },
  { name: 'Okra (Bhindi)', seasons: ['Kharif', 'Summer'] },
  { name: 'Cabbage', seasons: ['Rabi'] },
  { name: 'Cauliflower', seasons: ['Rabi'] },
  { name: 'Capsicum', seasons: ['Rabi', 'Summer'] },
  { name: 'Chilli', seasons: ['Kharif', 'Rabi'] },
  { name: 'Cucumber', seasons: ['Summer', 'Kharif'] },
  { name: 'Bottle Gourd', seasons: ['Summer', 'Kharif'] },
  { name: 'Bitter Gourd', seasons: ['Summer', 'Kharif'] },
  { name: 'Pumpkin', seasons: ['Kharif', 'Rabi'] },
  { name: 'Spinach', seasons: ['Rabi', 'Summer'] },
  { name: 'Fenugreek (Methi)', seasons: ['Rabi'] },
  { name: 'Coriander', seasons: ['Rabi', 'Kharif'] },
  { name: 'Banana', seasons: ['Year-round'] },
  { name: 'Mango', seasons: ['Summer'] },
  { name: 'Apple', seasons: ['Rabi'] },
  { name: 'Grapes', seasons: ['Rabi'] },
  { name: 'Orange', seasons: ['Rabi'] },
  { name: 'Pomegranate', seasons: ['Kharif', 'Rabi'] },
  { name: 'Papaya', seasons: ['Year-round'] },
  { name: 'Guava', seasons: ['Rainy', 'Winter'] },
  { name: 'Pineapple', seasons: ['Kharif'] },
  { name: 'Tea', seasons: ['Year-round'] },
  { name: 'Coffee', seasons: ['Year-round'] },
  { name: 'Rubber', seasons: ['Year-round'] },
  { name: 'Turmeric', seasons: ['Kharif'] },
  { name: 'Ginger', seasons: ['Kharif'] },
  { name: 'Cardamom', seasons: ['Kharif'] },
  { name: 'Cumin (Jeera)', seasons: ['Rabi'] },
  { name: 'Coriander Seed', seasons: ['Rabi'] }
];

export const normalizeCropName = (name = '') => String(name).trim().toLowerCase();

export const getCropByName = (name = '') => {
  const normalized = normalizeCropName(name);
  return CROP_CATALOG.find((crop) => normalizeCropName(crop.name) === normalized) || null;
};
